version: "3.4"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    volumes:
      - data:/var/lib/mysql
    networks:
      - banshee
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PW_ROOT}
    ports:
      - "3316:3306"
    restart: always
  destiny-mod-bot:
    depends_on: [ mariadb ]
    container_name: DestinyModBot
    build: .
    networks:
      - banshee
    links:
      - mariadb:mariadb
    restart: always
    environment:
      - D_TOKEN=${D_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_DB=${DB_DB}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_AUTOCOMMIT=${DB_AUTOCOMMIT}
      - DB_PORT=${DB_PORT}
      - DB_PW_ROOT=${DB_PW_ROOT}
networks:
  banshee:
    external: 
      name: banshee.local
volumes:
  data:
